server:
  port: 8080
  servlet:
    context-path: / #项目名称
    session.timeout: P0DT60M0S #D天H小时M分钟S秒，字符T是紧跟在时分秒之前的，每个单位都必须由数字开始,且时分秒顺序不能乱
    encoding:
      force: true
      charset: utf-8
      enabled: true
  error:
    include-exception: true
    include-message: always
#  ssl: #https证书配置 配置了之后只能通过https访问应用
#    key-store: xxx.pfx 证书文件
#    key-store-password:  1234 证书密码

#配置日志
logging:
  level:
    net.mingsoft: debug
  config: classpath:log4j-spring.xml

ms:
  #scheme: https #解决使用代理服务器代理应用时标签解析域名依旧为http的问题
  xss:
    enable: false #xss过滤器的开关
    filter-url: /**   #过滤的url,多个用逗号分开
    #如果怕设置后台过滤麻烦，直接排除 /ms/**
    exclude-url: /ms/mdiy/formData/update.do,/ms/mdiy/model/data/update.do,/ms/cms/content/update.do,/ms/mdiy/formData/save.do,/ms/mdiy/model/data/save.do,/ms/cms/content/save.do,/ms/mdiy/model/updateJson.do,/ms/mdiy/form/updateJson.do,/static/**,/template/**,/file/upload.do,/static/plugins/ueditor/1.4.3.3/jsp/editor.do  #排除的url,多个用逗号分开

  diy:
    html-dir: html

  swagger:
    enable: false #启用swagger文档，生产的时候务必关掉 访问地址：http://ip|域名/项目发布名/swagger-ui.html

  manager:
    path: /ms #后台访问的路径，如:http://项目/ms/login.do，生产的时候建议修改
    check-code: true #默认开启验证码验证，false验证码不验证

  upload:
    enable-web: false  #启用web层的上传
    template: template #模板文件夹支持重命名，不支持路径
    path: upload #文件上传路径，可以根据实际写绝对路径
    mapping: /upload/** #修改需要谨慎，系统第一次部署可以随意修改，如果已经有了上传数据，再次修改会导致之前上传的文件404
    denied: exe,jsp,xml,sh,bat,py,ftl,jspx
    back-up: /upload_back
    multipart:
      #最大上传文件大小 单位：KB
      max-file-size: 104857600
      #文件暂存临时目录
      upload-temp-dir: temp
      #临时文件大小
      max-in-memory-size: 10240000
      #总上传最大大小 单位：KB -1禁用
      max-request-size: -1

  #shiro-key:  #16位长度，不填写默认随机生成
  cookie-name: SHIRO_SESSION_ID

  rand-code:
    length: 4 #验证码长度
    circle: 10 #干扰线条数，值越大越不容易辨别

spring:
  main:
    allow-circular-references: true
  datasource:
    druid:
      initialSize: 5 #初始连接数，默认0
      minIdle: 5  #最小连接数，默认8
      maxActive: 20 #最大连接数，默认8
      maxWait: 2000 #获取连接的最大等待时间，单位毫秒
      validationQuery: SELECT 1
      testOnBorrow: true #设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true #设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      poolPreparedStatements: true #可以支持PSCache（提升写入、查询效率）
      filters: stat,wall #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      keepAlive: true #保持长连接
      stat-view-servlet:
        enabled: false #启用druid监控
  profiles:
    active: dev
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      use-suffix-pattern: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
  servlet:
    multipart:
      max-request-size: 100MB
      enabled: false
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    template-loader-path: file:WEB-INF/,file:WEB-INF/manager,classpath:/,classpath:/WEB-INF/manager,classpath:/WEB-INF
    settings:
      template_update_delay: 1
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      select-strategy: not_empty
  configuration:
    database-id: mysql
